# Generated by Django 4.2 on 2023-04-05 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ijara_uz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
