# Generated by Django 4.2 on 2023-04-05 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ijara_uz', '0003_remove_customuser_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'CustomUser'},
        ),
    ]
