# Generated by Django 4.2 on 2023-04-05 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ijara_uz', '0007_apartment'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='contract',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='for_men',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='is_flat',
            field=models.BooleanField(default=True),
        ),
    ]
