# Generated by Django 4.2 on 2023-04-05 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ijara_uz', '0008_apartment_contract_apartment_for_men_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ijara_uz.user'),
            preserve_default=False,
        ),
    ]
