# Generated by Django 4.2 on 2023-04-07 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ijara_uz', '0011_customuser_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='email',
        ),
    ]
