# Generated by Django 4.2 on 2023-04-07 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ijara_uz', '0014_alter_jobs_list_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='list_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
